steps:
  - label: "Test"
    command: "nix develop --command make test"

  - label: "Cross build"
    command: "nix develop --command make crossbuild"

  - label: "Formatting"
    command: 'test -z "$(nix develop --command gofmt -l .)"'
